name: school_platform
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  intl: ^0.17.0
  dio_cache_interceptor: ^3.0.0
  dio_cache_interceptor_hive_store: ^4.0.0
  get: ^4.7.2
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  http: ^0.13.6
  youtube_player_flutter: ^9.1.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.0.14
  open_file: ^3.2.1
  file_picker: ^9.0.0
  url_launcher: ^6.1.7
  mysql1: ^0.20.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.15
  fl_chart: ^0.70.2
  screen_protector: ^1.4.2+1
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  google_fonts: 4.0.4



dependency_overrides:
  fl_chart:
    git:
      url: https://github.com/imaNNeoFighT/fl_chart.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# App icon configuration:
# This configuration uses the image located at "lib/codea.png" as the app icon for both Android and iOS.
flutter_icons:
  android: true
  ios: true
  image_path: "lib/h.png"